commerce/auctions/urls.py
from django.urls import path
from . import views

app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    path("customer", views.customer, name="customer"),

    path("<int:listing_id>", views.listing, name="listing"),
    

    path("category", views.category, name="category"),
    path("bid", views.bid, name="bid"),

    path("watchlist", views.watchlist, name="watchlist"),
    path("<int:listing_id>/addToWatchlist", views.addToWatchlist, name="addToWatchlist"),
    path("removeFromWatchlist/<str:pk>/", views.removeFromWatchlist, name="removeFromWatchlist"),

    path("myListing", views.my_listing, name="myListing"),
    path("add", views.add, name="add"),
    path("update_mylisting/<str:pk>/", views.updateMyListing, name="update_mylisting"),
    path("delete_mylisting/<str:pk>/", views.deleteMyListing, name="delete_mylisting"),
]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls")),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.datetime_safe import date

        
STATUS = [
    ('ACTIVE', 'Active'),
    ('CLOSED', 'Closed')
]


class User(AbstractUser):
    first = models.CharField(max_length=64, null=True)
    last = models.CharField(max_length=64, null=True)
    birth_date = models.DateField(default=date.today, null=True)
    joined_on = models.DateField(default=date.today, null=True)
    is_creator = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.username} (id: {self.id}) creator: {self.is_creator}"



class Category(models.Model):
    category_name = models.CharField(max_length=64, null=True)
    is_category = models.BooleanField(default=False)
    
    def __str__(self):
        return self.category_name



class Listing(models.Model):
    title = models.CharField(max_length=64, null=True)
    description = models.TextField(max_length=500, blank=True, null=True)
    starting_bid = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    current_price = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    image_url = models.ImageField(blank=True, null=True, upload_to="images/")
    # Each Listing is related to one category
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, limit_choices_to={'is_category': True})
    creator = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="listings")
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    status = models.CharField(max_length=200, null=True, choices=STATUS)
    follow = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title} followed: {self.follow} status: {self.status} creator: {self.creator}"

    @property
    def imageUrl(self):    
        if self.image_url and hasattr(self.image_url, 'url'):
            return self.image_url.url
        else:
            return "/media/images/noPhoto.jpeg"



class Comment_Auction_Listing(models.Model):
    comment_text = models.TextField(max_length=500, blank=True, null=True)
    like_count = models.IntegerField(default=0, null=True)



class Watchlist(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    listing = models.ManyToManyField(Listing, blank=True, related_name="listings")

    def __str__(self):
        return f"Watchlist of {self.user}"



class Bid(models.Model):
    LEAST_AS_LARGE_STARTINGBID = 'LALS'
    GREATER_THAN_OTHER = 'GTO'
    ERROR_MESSAGE = [
        (LEAST_AS_LARGE_STARTINGBID, 'Your bid must be at least as large as the startingbid.'),
        (GREATER_THAN_OTHER, 'Your bid does not exceed existing bid!'),
    ]
    start_price = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    placed_bid = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    highest_bidder = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    bid_error = models.CharField(
        max_length=100,
        error_messages = ERROR_MESSAGE,
        null=True
    )

    def __str__(self):
        return f"start price:{self.start_price} - placed bid:{self.placed_bid} - highest bidder: {self.highest_bidder} id: {self.id}"


class Customer(models.Model):
    listings = models.ManyToManyField(Listing, blank=True, related_name="customers")
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    isHighestBidder = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user}, highest bidder? {self.isHighestBidder} - id: {self.id}"

commerce/auctions/forms.py
from django import forms
from .models import Listing, Watchlist


class CreateListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ['title', 'description', 'starting_bid',
                   'image_url', 'category', 'status']
        widgets = {
            'title': forms.TextInput(
				   attrs={'class': 'form-control'}),
            'description': forms.Textarea(
				   attrs={'class': 'form-control', 'row': '3'}),
            'starting_bid': forms.NumberInput(
				   attrs={'class': 'form-control'}),
            'category': forms.Select(
                attrs={'class': 'form-control'}),
            'status': forms.Select(
                attrs={'class': 'form-control'}),
        }
        labels = {
            'title': ('Title'),
            'description': ('Description'),
            'starting_bid': ('Starting bid'),
            'image_url': ('Image'),
            'category': ('Category'),
            'status': ('Status')
        }


# Creating a form to add an listing
# form = CreateListingForm()

# Creating a form to change an existing listing
# listing = Listing.objects.get(pk=1)
# form = CreateListingForm(instance=listing)

commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse

from .models import Customer, User, Listing, Watchlist
from .forms import CreateListingForm


def index(request):
    # Only the active listings
    return render(request, "auctions/index.html", {
        "listings": Listing.objects.filter(status='ACTIVE')
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        first = request.POST["first"]
        last = request.POST["last"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username=username, first=first, last=last, email=email, password=password)
            user.save()
            # Create Customer, one to one with user (own addition)
            Customer.objects.create(
                user = user,
                )
            # Add Watchlist to the user (own addition)
            Watchlist.objects.create(
                user = user,
            )
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")
        


@login_required
def customer(request):
    user = request.user
    costumer = user.costumer
    
    
    return render(request, "auctions/watchlist.html", {
        "costumer": costumer,
    })



@login_required
def listing(request, listing_id):
    listing = Listing.objects.get(id=listing_id)
    customers = listing.customers.all()
    return render(request, "auctions/listing.html", {
        "listing": listing,
        "customers": customers,
    })




@login_required
def my_listing(request):
    return render(request, "auctions/myListing.html", {
        "listings": Listing.objects.filter(creator=request.user)
    })

@login_required
def add(request):
    if request.method == "POST":
        form = CreateListingForm(request.POST, request.FILES)
        if form.is_valid():
            listing = form.save(commit=False)

            # Add creator to the listing
            creator = request.user
            listing.creator = creator
            listing.save()
            creator.is_creator = True

            return HttpResponseRedirect(reverse("auctions:myListing"))

        # Form not valid, re-render the page with existing information
        else:
            return render(request, "auctions/add.html", {
            "form": form 
            })

    # If method is GET, render an empty Create form
    return render(request, "auctions/add.html", {
        "form": CreateListingForm()
    })
    

@login_required
def updateMyListing(request, pk):
    listing = Listing.objects.get(id=pk)
    form = CreateListingForm(instance=listing)

    if request.method == "POST":
        form = CreateListingForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return render(request, "auctions/myListing.html")

        else:
            return render(request, "auctions/myListing.html", {
                "form": form
            })


@login_required
def deleteMyListing(request, pk):
    listing = Listing.objects.get(id=pk)
    if request.method == "POST":
        listing.delete()
        return render(request, "auctions/myListing.html")

    return render(request, "auctions/delete.html", {
         "listing": listing 
    })




@login_required
def watchlist(request):
    watchlist = Watchlist.objects.get(user=request.user)
    listings = watchlist.listing.all()
    total_listings = listings.count()
    
    return render(request, "auctions/watchlist.html", {
        "listings": listings,
        "total_listings": total_listings
    })

@login_required
def addToWatchlist(request, listing_id):
    listing = Listing.objects.get(pk=listing_id)
    if listing.follow == True:
        return render(request, "auctions/index.html", {
            "listings": Listing.objects.filter(status='ACTIVE'),
            "message": "Item already on your watchlist."
        })   
    else:
        listing.follow = True
        listing.save()
        watchlist = Watchlist.objects.get(user=request.user)
        watchlist.listing.add(listing)

        return HttpResponseRedirect(reverse("auctions:watchlist")) 


@login_required
def removeFromWatchlist(request, pk):
    listing = Listing.objects.get(id=pk)
    listing.follow = False
    listing.save()

    watchlist = Watchlist.objects.get(user=request.user)
    watchlist.listing.remove(listing)

    listings = watchlist.listing.all()
    total_listings = listings.count()
    
    return render(request, "auctions/watchlist.html", {
        "listing": listing,
        "listings": listings,
        "total_listings": total_listings,
        "message": "is removed from your watchlist."
    })




@login_required
def category(request):
    return render(request, "auctions/category.html")

@login_required
def bid(request):
    return render(request, "auctions/bid.html")

commerce/auctions/templates/auctions/add.html
{% extends "auctions/layout.html" %}

{% block title %}Create Listing{% endblock %}

{% block body %}
    <div class="px-2">
        <h3>Create a new listing</h3>
        <h6>All fields are required, except Image</h6>
        <br>

        <div class="form-group">
            <!-- this form accepts media using attribute: enctype -->
            <form action="{% url 'auctions:add' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success btn-block">Submit</button>   
            </form>
        </div>
        <a href="{% url 'auctions:index' %}">View Active Listings</a>
    </div>
{% endblock %}

commerce/auctions/templates/auctions/bid.html
{% extends "auctions/layout.html" %}

{% block title %}Placing bid{% endblock %}

{% block body %}

    <h2>Bidding</h2>
    
    <div class="form-group">
        <form action="{% url 'auctions:bid' %}" method="post">
            {% csrf_token %}
            <input type="number" name="bid" placeholder="€"/><br/><br/>
            <!-- {{ form.as_p }} -->
            <button type="submit" class="btn btn-outline-success btn-block">Submit</button>   
        </form>
    </div>

{% endblock %}

commerce/auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block title %}Category{% endblock %}

{% block body %}
    <h1>Category</h1>

    

{% endblock %}

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %} 

{% block title %}Dashboard{% endblock %}

{% block body %}
	<div class="px-2">
		{% if message %}
			<div>{{ message }}</div>
		{% endif %}

		<h5>Active auctions</h5>
		<!-- <div class="d-flex justify-content-around flex-wrap px-2"> -->
		
		<div class="row">
			{% for listing in listings %}
			<div class="col-sm-4">
				<div class="card border-info mb-2 ml-3" style="width: 16rem;">
					<!-- <div class="embed-responsive embed-responsive-1by1"> -->
						<img src="{{ listing.imageUrl }}" class="card-img-top" id="index-image" alt="img" />
					<!-- </div> -->
					
					<div class="card-body">
						{% if user.is_authenticated %}
							<a href="{% url 'auctions:listing' listing.id %}"><h5 class="card-title">{{ listing.title }}</h5></a>
						{% else %}
							<h5 class="card-title">{{ listing.title }}</h5>
						{% endif %}
						<p class="card-text">{{ listing.description }}</p>
					</div>
					<ul class="list-group list-group-flush">
						<li class="list-group-item"><p>Price: €{{ listing.starting_bid }}</p></li>
						<li class="list-group-item"><p>Created {{ listing.date_created }} by {{ listing.creator }}</p></li> 
					</ul>
				</div>
			</div>
			{% endfor %}
		</div>	
		
		<!-- </div> -->
	</div>
{% endblock %}



<!-- embed-responsive-item -->

commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1 class="pl-2">Auctions</h1>
        <!-- NavBar -->
        <nav class="navbar navbar-expand-sm bg-info navbar-dark sticky-top" id="navbar">
            <!-- Brand -->
            <a class="navbar-brand pl-2" href="{% url 'auctions:index' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="url(#grad1)" class="bi bi-intersect" viewBox="0 0 16 16">
                    <path d="M0 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v2h2a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-2H2a2 2 0 0 1-2-2V2zm5 10v2a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1h-2v5a2 2 0 0 1-2 2H5zm6-8V2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h2V6a2 2 0 0 1 2-2h5z"/>
                    <defs>
                        <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="0%">
                          <stop offset="0%" style="stop-color:rgb(255,255,0);stop-opacity:1" />
                          <stop offset="100%" style="stop-color:rgb(255,0,0);stop-opacity:1" />
                        </linearGradient>
                      </defs>
                </svg>
            </a>
            <!-- Toggle button for mobile nav -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon text-light"></span>
            </button>

            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav mr-auto mt-lg-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'auctions:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'auctions:watchlist' %}">Watchlist</a>
                        </li>
                        
                        <!-- Dropdown -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Fashion</a>
                                <a class="dropdown-item" href="#">Toys & Games</a>
                                <a class="dropdown-item" href="#">Electronics</a>
                                <a class="dropdown-item" href="#">Home</a>
                                <a class="dropdown-item" href="#">Antique</a>
                                <a class="dropdown-item" href="#">Baby</a>
                                <a class="dropdown-item" href="#">Computer & Accessories</a>
                                <a class="dropdown-item" href="#">Video Games</a>
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'auctions:add' %}">Create Listing</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'auctions:myListing' %}">My Listings</a>
                        </li>
                    
                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'auctions:logout' %}">Log Out</a>
                        </li>

                        <li class="nav-item">
                            <p class="font-weight-lighter font-italic ml-5 my-2 mr-2">Signed in as <strong>{{ user.username }}</strong>.</p>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link text-light active" href="{% url 'auctions:login' %}">Log In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light active" href="{% url 'auctions:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <p class="font-weight-lighter ml-5 my-2 mr-2">&#x1F399<i><b>New</b></i> to Auctions, register and join the fun!</p>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <br>
        <hr>

        {% block body %}
        {% endblock %}

        <!-- Bootstrap JavaScript -->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>

commerce/auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block title %}Listing{% endblock %}

{% block body %}
    <div class="px-2">
        <h3>{{ listing.title }}</h3>
        <div class="card border-info mb-3" style="max-width: 960px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="{{ listing.imageUrl }}" class="card-img-top" alt="img" />
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">{{ listing.description }}</p>
                        <p class="card-text">Created {{ listing.date_created }} by TODO</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><p>Starting bid: €{{ listing.starting_bid }}</p></li> 
                        <li class="list-group-item"><p>Current price: €{{ listing.current_price }}</p></li>
                    </ul>
                    <div class="card-body">
                        <a href="{% url 'auctions:bid' %}" class="card-link">Place bid</a>
                        <a href="{% url 'auctions:addToWatchlist' listing.id %}" class="card-link">Add to Watchlist</a>
                        <a href="#" class="card-link">Comment</a>
                    </div>
                </div>
            </div>
        </div>  
        <h5>Participants in this auction</h5>
        <div class="card border-info mb-3" style="max-width: 18rem;">
            <ul class="list-group list-group-flush">
                {% for customer in customers %}
                    <li class="list-group-item">{{ customer }}</li>
                {% empty %}
                    <li class="list-group-item">No participants</li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-success" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

commerce/auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block title %}WatchList{% endblock %}

{% block body %}
	<div class="px-2">
		{% if message %}
            <div>{{ listing }}{{ message }}</div>
        {% endif %}

		<h6>Watching {{ total_listings }} listings</h6>
		{% for listing in listings %}
			<div class="card mb-3" style="max-width: 800px;">
				<div class="row g-0">
					<div class="col-md-4">
						<img src="{{ listing.imageUrl }}" class="img-fluid rounded-start" alt="...">
					</div>
					<div class="col-md-6">
						<div class="card-body">
							<a href="{% url 'auctions:listing' listing.id %}"><h5 class="card-title">{{ listing.title }}</h5></a>
							<p class="card-text">{{ listing.description }}</p>
							<p>Current price: €{{ listing.current_price }}</p>
							<p class="card-text"><small class="text-muted">Category:</small></p>
							<p class="card-text"><small class="text-muted">Status: {{ listing.status }}</small></p>
							<p class="card-text"><small class="text-muted">Created {{ listing.date_created }} by {{ listing.creator }}</small></p>
						</div>
					</div>
					<div class="col-md-2">
						<a class="btn btn-outline-success" href="">Bid</a><br><br>
						<a class="btn btn-outline-success" href="{% url 'auctions:removeFromWatchlist' listing.id %}">Remove</a>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>

{% endblock %}